export const WEATHER_LOADING = "WEATHER_LOADING";
export const WEATHER_FAILED = "WEATHER_FAILED";
export const WEATHER_UPDATE = "WEATHER_UPDATE";
export const FORECAST_UPDATE = "FORECAST_UPDATE";
export const FETCH_WEATHER_DETAILS = "FETCH_WEATHER_DETAILS";
export const FETCH_WEATHER_FORECAST = "FETCH_WEATHER_FORECAST";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";